### ISSUE TITLE
v1.2.1 broken build

### ISSUE THREAD

**Issue by ccsaposs** [MarcelloTheArcane/netlify-plugin-csp-generator#11]
Hi,

I wanted to give you a heads up that it looks like the current version (1.2.1) is broken.  I noticed that the latest commit on master seems to fix the issue, but it seems like that fix isn't in 1.2.1 (wanted to let you know just in case you aren't already aware).

Here's a branch where the build is broken: https://github.com/valueourminds/website/pull/38
And the Netlify deploy log: https://app.netlify.com/sites/website-40342a/deploys/5f7facb0ee1b790008db7214

**Comment by MarcelloTheArcane** [comment]
@ccsaposs Thanks for reporting, I've just pushed a fix to v1.2.2.

Sorry for the inconvenience.

**Comment by ccsaposs** [comment]
No worries, it wasn't an inconvenience for us at all.  Thank you for supporting this plugin!
