### ISSUE TITLE
Support for inline events

### ISSUE THREAD

**Issue by JohnFitz** [MarcelloTheArcane/netlify-plugin-csp-generator#12]
Hey, 

I was wondering how I might go about adding support for inline events? [Filament Group/Scott Jehl](https://www.filamentgroup.com/lab/load-css-simpler/) has a nice, simple way to delay loading the non-critical CSS so it doesn't block page rendering.
```html
<link rel="stylesheet" href="css/non-critical-css.css" media="print" onload="this.media='all'; this.onload=null;">
    <noscript><link rel="stylesheet" media="all" href="css/non-critical-css.css"></noscript>
```
Obviously one could achieve this in a `<script>` block later in the head, but I like how declarative this feels.

I had a look at your code but I'm missing something. I've marked the lines I've added with `//  <---<<`. 
The issue I'm running into is that I end up with two `script-src-attr` directives per policy. One has the hash generated here in your `createFileProcessor` function, the other has `'unsafe-hashes'` coming from my `netlify.toml`
```javascript 
function createFileProcessor (buildDir, disableGeneratedPolicies) {
  return path => file => {
    const dom = new JSDOM(file)
    const shouldGenerate = (key) => !(disableGeneratedPolicies || []).includes(key)
    const generateHashesFromElement = generateHashes(dom, element => element.innerHTML)
    const generateHashesFromStyle = generateHashes(dom, element => element.getAttribute('style'))
    const generateHashesInlineEvent = generateHashes(dom, element => element.getAttribute('onload')) //  <---<< Just trying to get onload working initially

    const scripts = shouldGenerate('scriptSrc') ? generateHashesFromElement('script') : []
    const styles = shouldGenerate('styleSrc') ? generateHashesFromElement('style') : []
    const inlineStyles = shouldGenerate('styleSrc') ? generateHashesFromStyle('[style]') : []
    const inlineEvents = shouldGenerate('scriptSrcAttr') ? generateHashesInlineEvent('[onload]') : [] //  <---<< 

    const indexMatcher = new RegExp(`^${buildDir}(.*)index\\.html$`)
    const nonIndexMatcher = new RegExp(`^${buildDir}(.*\\/).*?\\.html$`)

    let webPath = null
    let globalCSP = null
    if (path.match(indexMatcher)) {
      webPath = path.replace(indexMatcher, '$1')
      globalCSP = false
    } else {
      webPath = path.replace(nonIndexMatcher, '$1*')
      globalCSP = true
    }

    const cspObject = {
      scriptSrc: scripts,
      styleSrc: [...inlineStyles, ...styles],
      scriptSrcAttr: inlineEvents //  <---<< 
    }

    return {
      webPath,
      cspObject,
      globalCSP,
    }
  }
}
```
I'd be grateful for any insights :pray:

**Comment by JohnFitz** [comment]
Never mind, it was a silly mistake. I'd somehow managed to kebab case the directive in the netlify.toml file. It works fine now with onload events.

**Comment by MarcelloTheArcane** [comment]
Hello @JohnFitz!

Thanks for your issue, feel free to make a pull request for this if you like.  

Watch out using `scriptSrcAttr`, it's not supported in Firefox - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src-attr#Browser_compatibility
