### ISSUE TITLE
Testing with "Report-Only"

### ISSUE THREAD

**Issue by chrisfinazzo** [MarcelloTheArcane/netlify-plugin-csp-generator#14]
Using the plugin, is there a way to apply the [Report-Only][] header for the policy we define in TOML? I previously did this via a `_headers` file, and would get feedback in Chrome's DevTools which I could watch to winnow down the areas I needed to address as I built out a policy.

Thinking about how I could test a policy before it goes "live", if only to catch any mistakes.

[Report-Only]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only

**Comment by MarcelloTheArcane** [comment]
I'll have to have a look and see how that works

**Comment by MarcelloTheArcane** [comment]
Hey @chrisfinazzo!  This should be fixed now.  You'll need to use version `^1.3.0`, and then need to edit your `netlify.toml`.  Happy to help out if you get stuck.

```diff
[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"
+ reportURI = "<some-uri>"
+ reportTo = "csp-violation-reporter"
+ reportOnly = true # You can make this false and it will enable the policies and also report

  [plugins.inputs.policies]
    # Your policies

[[headers]]
  for = "/*"
    [headers.values]
+   Reporting-Endpoints = "csp-violation-reporter=\"<some-uri>\""

```

**Comment by chrisfinazzo** [comment]
![So Close](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

Oy. I think I may be missing something [here](https://hirechrisfinazzo.com) as my site doesn't load completely. My config is below.

    [[plugins]]
    package = "netlify-plugin-csp-generator"
    [plugins.inputs]
    buildDir = "build"
    reportURI = "https://chrisfinazzo.report-uri.com/r/d/csp/reportOnly"
    reportTo = "csp-violation-reporter"
    reportOnly = true
    [plugins.inputs.policies]
      defaultSrc = "'self'"
      fontSrc = "'self'"
      imgSrc = "'https:'"
      styleSrc = "'PyUkwePEiCLvmEoFP/CJwgoN8RD9bh4iFRGiA+SojkY= https://use.fontawesome.com;'"
      connectSrc = "'self'"
      formAction = "'https://formspree.io/f/xgerekvv'"
      frameAncestors = "'none'"
      workerSrc = "'self'"

       [[headers]]
      for = "/*"
      [headers.values]  
        cache-control = '''
        max-age=0,
        public,
        must-revalidate,
        no-transform'''
        Reporting-Endpoints = csp-violation-reporter=\"https://chrisfinazzo.report-uri.com/r/d/csp/reportOnly"\
        Upgrade-Insecure-Requests = "1"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"


Alternatively, could I use StyleSrc 'self' and ScriptSrc 'self' to do the job? In that case, it might not matter that the file hash has changed.
