### ISSUE TITLE
CSP header should not be sent with stylesheets, scripts and images

### ISSUE THREAD

**Issue by jackdbd** [MarcelloTheArcane/netlify-plugin-csp-generator#18]
Currently the `content-security-policy` (or `content-security-policy-report-only`) response header is sent with all HTML files and assets (stylesheets, images, scripts).

![Selection_004](https://user-images.githubusercontent.com/5048090/117965378-fbd17400-b322-11eb-87c5-85a58e6ab3f9.png)

Webhint [warns against this](https://webhint.io/docs/user-guide/hints/hint-no-html-only-headers/) because it represents header bloat.

Avoid sending the CSP header with stylesheets and images should be ok. However, I think that with scripts the situation is a bit more complicated, since they do create a **new execution context** when they are loaded as web workers.

> If a resource does not create a new execution context (for example, when including a script, image, or stylesheet into a document), then any policies delivered with that resource are discarded without effect.
https://stackoverflow.com/a/37819481/3036129

The CSP header can be really heavy (I have previously seen a 4kB CSP header on my website), so it contributes significantly to header bloat.

See also:

- [What does it mean to set a Content Security Policy on response to a non-HTML request?](https://stackoverflow.com/questions/37819249/what-does-it-mean-to-set-a-content-security-policy-on-response-to-a-non-html-req/37819481)
- [Content Security Policy (CSP) Header: Onto each file or only the actual HTML pages?](https://stackoverflow.com/questions/54203764/content-security-policy-csp-header-onto-each-file-or-only-the-actual-html-pag)
- [Policy applicability](https://www.w3.org/TR/CSP2/#which-policy-applies)

**Comment by MarcelloTheArcane** [comment]
Sorry, I didn't see this issue!

Yes, that's fine - you can exclude currently, but it would be nice to be able to tell, and do it automatically.

I'll look into it.

**Comment by MarcelloTheArcane** [comment]
I've pushed a new commit (v1.4.0) which will hopefully fix this issue.  Could you take a look?

What I think was happening is that it was generating a wildcard header (`/*`) because there's some html files that aren't called `index.html`.

Now I've changed it so it will create a wildcard header called `/*.html` which will stop it being used for js/css/other files.

Let me know if it doesn't work, and I'll try something else!
