### ISSUE TITLE
Plugin does not add headers when Netflify redirect is applied

### ISSUE THREAD

**Issue by enclave-alistair** [MarcelloTheArcane/netlify-plugin-csp-generator#20]
Hi; thanks for the plugin, just running into a slight problem to do with the `*.html` wildcard that gets applied.

We host our React app on netlify, and use react-router converting `https://ourdomain.com/any/route/value` into meaningful application state.

We only have a single `index.html` file, and a netlify redirect in our `netlify.toml` to return our index page for any non-existent routes:

```
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
```

So `/any/route/value` actually serves `/index.html`.  However, it looks like `_headers` looks at the URL rather than the file.

What we see is that the root URL of the site (the actual index.html path) has a CSP header, but the redirected URLs do not.

I'm guessing this is due to the URL matching that gets written to the `_headers` file.

Is there a way we can either say "all files that don't have an extension", or just "all files" if need be?

This is probably related to #18.

**Comment by MarcelloTheArcane** [comment]
Hello Alistair, thanks for the issue!

Unfortunately I think this is expected behaviour, as SPAs aren't supported by this plugin 🙁 

This is because the plugin looks through all the generated code, finds the one `index.html` file, and generates CSP headers based on that content.  It doesn't know anything about the other URLs that map to that file, because it assumes a 1:1 relationship between generated pages and URLs.

I'm afraid I don't have a solution that could work, other than using [Gatsby](https://www.gatsbyjs.com) which I believe works.

I'm happy to add a "all files that don't have an extension"/"all files" setting if it'd work, would you be able to share your repository privately with me so I can test it out?

**Comment by enclave-alistair** [comment]
An 'all files that don't have an extension' flag would be perfect (or just 'all files' if a pattern match for 'no extension' is tricky).

The only files in the SPA that have an extension are the static resource files, which don't need the CSP header.

I can't share the actual repository, but I will put together a minimal recreate repo and share that with you.

**Comment by enclave-alistair** [comment]
Sorry for the delay, just had to find some time do this properly.

I've set up an example repo here: https://github.com/enclave-alistair/react-router-netlify.

I've also put this on netlify here: https://wizardly-meitner-d2f5b2.netlify.app/.

You'll see that clicking the nav links changes the URL.

Fundamentally, if I visit https://wizardly-meitner-d2f5b2.netlify.app, the CSP header is there; if I visit https://wizardly-meitner-d2f5b2.netlify.app/dashboard (best to do it in a new tab), it is not.

**Comment by MarcelloTheArcane** [comment]
Thanks, I'll have a look over the next couple of days...

**Comment by MarcelloTheArcane** [comment]
I tried deploying it on Netlify so I could get the build directory, but it throws errors with dependencies that I don't know how to fix 🙁

**Comment by enclave-alistair** [comment]
Not sure why you weren't able to build it on Netlify, but I've attached a zip file containing the full build output from the above netlify site.

[netlify-spa-deploy.zip](https://github.com/MarcelloTheArcane/netlify-plugin-csp-generator/files/6905563/netlify-spa-deploy.zip)

**Comment by MarcelloTheArcane** [comment]
I've pushed #21 to [v1.5.0](https://www.npmjs.com/package/netlify-plugin-csp-generator/v/1.5.0) now - this adds the following option which you can add:

```diff
[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
+ generateForAllFiles = true
```

This will make Netlify return the relevant path's CSP header from `_headers` for any file.  There is a caveat though, that it can only parse the root `index.html` and has no idea about other paths, so you'll have to have a less restrictive Content-Security-Policy.

I hope this works for you, and let me know if you come across any more problems!

**Comment by alistairjevans** [comment]
Thanks @MarcelloTheArcane. 🚀

The requirement to only parse index.html will work just fine, because we only have the one HTML file anyway. The redirects we ask netlify to do should now have the right headers.
